allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter() // Ensure jcenter() is included for resolving legacy dependencies
    }
}

rootProject.buildDir = "../build"

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"

    repositories {
        google()
        mavenCentral()
        jcenter() // Ensure jcenter() is accessible for all subprojects
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
